---
allowedOrigins:
  - http://localhost:3000
  - http://localhost:3001
database:
    driverClass: org.postgresql.Driver
    user: postgres
    password: ${DB_PASS}
    url: jdbc:postgresql://localhost:5432/postgres
    properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    maxWaitForConnection: 1s
    validationQuery: "/* MyApplication Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
